name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: mg-runner

    steps:
      - name: Checkout Workflows repository
        uses: actions/checkout@v2
        with:
          repository: aozcalisanmg/workflows
          path: workflows

      - name: Clone Mywebapp repository
        run: |
          git clone https://github.com/aozcalisanmg/mywebapp.git
          cd mywebapp
          git checkout main

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          cd mywebapp
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mywebapp:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/mywebapp:${{ github.sha }}

      - name: Run Trivy vulnerability scan
        run: |
          trivy image ${{ secrets.DOCKER_USERNAME }}/mywebapp:${{ github.sha }}
        continue-on-error: true

      - name: Clone Charts repository
        run: |
          git clone https://github.com/aozcalisanmg/charts.git
          cd charts
          git checkout main

      - name: Update Helm chart
        run: |
          cd charts
          sed -i 's/tag: .*/tag: ${{ github.sha }}/' charts/myapp-chart/values.yaml
          git config --global user.email "your-email@example.com"
          git config --global user.name "your-username"
          git add charts/myapp-chart/values.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push origin main

      - name: Login to ArgoCD
        run: |
          argocd login localhost:8080 --username admin --password ${{ secrets.ARGOCD_PASSWORD }} --insecure

      - name: Sync ArgoCD application
        run: |
          argocd app sync myapp
