name: CI/CD Pipeline

on: 
  workflow_dispatch:

env:
  APP_REPO: mywebapp
  GIT_USER: aozcalisanmg
  CHART_REPO: charts

jobs:
  BuildAndPush:
    name: BuildAndPush
    runs-on: mg-runner

    steps:
      - name: Cleanup workspace
        run: |
          rm -rf ${GITHUB_WORKSPACE}/*
          mkdir -p ${GITHUB_WORKSPACE}/ci-workdir
          
      - name: Checkout Workflows repository
        uses: actions/checkout@v2
        with:
          repository: ${{ env.GIT_USER }}/workflows
          path: workflows

      - name: Clone Mywebapp repository
        run: |
          git clone https://github.com/${{ env.GIT_USER }}/${{ env.APP_REPO }}.git
          cd ${{ env.APP_REPO }}
          git checkout main
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          cd ${{ env.APP_REPO }}
          docker build --pull -t ${{ secrets.DOCKER_USERNAME }}/${{ env.APP_REPO }}:${{ github.run_number }} . --no-cache  
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.APP_REPO }}:${{ github.run_number }}

  Security:
    name: Security
    runs-on: mg-runner
    needs: BuildAndPush

    steps:          
      - name: Run Trivy vulnerability scan
        run: |
          trivy image ${{ secrets.DOCKER_USERNAME }}/${{ env.APP_REPO }}:${{ github.run_number }}
        continue-on-error: true


  UpdatingHelmChart:
    name: UpdatingHelmChart
    runs-on: mg-runner
    needs: Security    

    steps:  
      - name: Clone Charts repository
        run: |
          git clone https://github.com/${{ env.GIT_USER }}/${{ env.CHART_REPO }}.git
          cd ${{ env.CHART_REPO }}
          git checkout main
      - name: Update Helm chart
        run: |
          cd ${{ env.CHART_REPO }}
          sed -i '' 's/tag: .*/tag: "${{ github.run_number }}"/' myapp-chart/values.yaml
          
          version=$(grep '^version:' myapp-chart/Chart.yaml | cut -d ' ' -f 2)
          appVersion=$(grep '^appVersion:' myapp-chart/Chart.yaml | cut -d '"' -f 2)
          newVersion=$(echo $version | awk -F. '{printf "%d.%d.%d", $1, $2, $3+1}')
          newAppVersion=$(echo $appVersion | awk -F. '{printf "%d.%d.%d", $1, $2, $3+1}')
          sed -i '' "s/^version:.*/version: $newVersion/" myapp-chart/Chart.yaml
          sed -i '' "s/^appVersion:.*/appVersion: \"$newAppVersion\"/" myapp-chart/Chart.yaml
          
          git add myapp-chart/values.yaml myapp-chart/Chart.yaml
          git commit -m "Update image tag to ${{ github.run_number }}"
          git push origin main

  ArgocdSyncApp:
    name: ArgocdSyncApp
    runs-on: mg-runner
    needs: UpdatingHelmChart       

    steps:  
      - name: Login to ArgoCD
        run: |
          argocd login localhost:8080 --username admin --password ${{ secrets.ARGOCD_PASSWORD }} --insecure
      - name: Sync ArgoCD application
        run: |
          argocd app set myapp --helm-set image.tag=${{ github.run_number }}        
          argocd app sync myapp --force --prune --replace
          
      - name: Cleanup working directory
        run: rm -rf ${GITHUB_WORKSPACE}/ci-workdir    
