name: CI/CD Pipeline

on: 
  workflow_dispatch:

jobs:
  BuildAndPush:
    name: BuildAndPush
    runs-on: mg-runner

    steps:
      - name: Cleanup workspace
        run: |
          rm -rf ${GITHUB_WORKSPACE}/*
          mkdir -p ${GITHUB_WORKSPACE}/ci-workdir
          
      - name: Checkout Workflows repository
        uses: actions/checkout@v2
        with:
          repository: aozcalisanmg/workflows
          path: workflows

      - name: Clone Mywebapp repository
        run: |
          git clone https://github.com/aozcalisanmg/mywebapp.git
          cd mywebapp
          git checkout main
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          cd mywebapp
          docker build --pull -t ${{ secrets.DOCKER_USERNAME }}/mywebapp:${{ github.sha }} . --no-cache  
          docker push ${{ secrets.DOCKER_USERNAME }}/mywebapp:${{ github.sha }}

  Security:
    name: Security
    runs-on: mg-runner
    needs: BuildAndPush

    steps:          
      - name: Run Trivy vulnerability scan
        run: |
          trivy image ${{ secrets.DOCKER_USERNAME }}/mywebapp:${{ github.sha }}
        continue-on-error: true


  UpdatingHelmChart:
    name: UpdatingHelmChart
    runs-on: mg-runner
    needs: Security    

    steps:  
      - name: Clone Charts repository
        run: |
          git clone https://github.com/aozcalisanmg/charts.git
          cd charts
          git checkout main
      - name: Update Helm chart
        run: |
          cd charts
          sed -i '' 's/tag: .*/tag: "${{ github.sha }}"/' myapp-chart/values.yaml
          
          version=$(grep '^version:' myapp-chart/Chart.yaml | cut -d ' ' -f 2)
          appVersion=$(grep '^appVersion:' myapp-chart/Chart.yaml | cut -d '"' -f 2)
          newVersion=$(echo $version | awk -F. '{printf "%d.%d.%d", $1, $2, $3+1}')
          newAppVersion=$(echo $appVersion | awk -F. '{printf "%d.%d.%d", $1, $2, $3+1}')
          sed -i '' "s/^version:.*/version: $newVersion/" myapp-chart/Chart.yaml
          sed -i '' "s/^appVersion:.*/appVersion: \"$newAppVersion\"/" myapp-chart/Chart.yaml
          
          git add myapp-chart/values.yaml myapp-chart/Chart.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push origin main

  ArgocdSyncApp:
    name: ArgocdSyncApp
    runs-on: mg-runner
    needs: UpdatingHelmChart       

    steps:  
      - name: Login to ArgoCD
        run: |
          argocd login localhost:8080 --username admin --password ${{ secrets.ARGOCD_PASSWORD }} --insecure
      - name: Sync ArgoCD application
        run: |
          argocd app set myapp --helm-set image.tag=${{ github.sha }}        
          argocd app sync myapp-development --force --prune --replace
          
      - name: Cleanup working directory
        run: rm -rf ${GITHUB_WORKSPACE}/ci-workdir    
