name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: mg-runner

    steps:
      - name: Cleanup workspace
        run: |
          rm -rf ${GITHUB_WORKSPACE}/*
          mkdir -p ${GITHUB_WORKSPACE}/ci-workdir
          
      - name: Checkout Workflows repository
        uses: actions/checkout@v2
        with:
          repository: aozcalisanmg/workflows
          path: workflows

      - name: Clone Mywebapp repository
        run: |
          git clone https://github.com/aozcalisanmg/mywebapp.git
          cd mywebapp
          git checkout main

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          cd mywebapp
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mywebapp:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/mywebapp:${{ github.sha }}

      - name: Run Trivy vulnerability scan
        run: |
          trivy image ${{ secrets.DOCKER_USERNAME }}/mywebapp:${{ github.sha }}
        continue-on-error: true

      - name: Clone Charts repository
        run: |
          git clone https://github.com/aozcalisanmg/charts.git
          cd charts
          git checkout main

      - name: Update Helm chart
        run: |
          cd charts
          sed -i '' 's/tag: .*/tag: "${{ github.sha }}"/' myapp-chart/values.yaml
          git add myapp-chart/values.yaml
          git commit -m "Update image tag to ${{ github.sha }}"

      - name: Push changes to Charts repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://${GITHUB_TOKEN}@github.com/aozcalisanmg/charts.git
          git push origin main

      - name: Login to ArgoCD
        run: |
          argocd login localhost:8080 --username admin --password ${{ secrets.ARGOCD_PASSWORD }} --insecure

      - name: Sync ArgoCD application
        run: |
          argocd app sync myapp

      - name: Cleanup working directory
        run: rm -rf ${GITHUB_WORKSPACE}/ci-workdir             
